"""salary_payroll_models

Revision ID: 24f6cbe8b8a9
Revises: e9b42a419f5f
Create Date: 2026-04-21 22:49:19.950899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24f6cbe8b8a9'
down_revision: Union[str, None] = 'e9b42a419f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('da', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('esi_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_salary_structure_name')
    )
    op.create_index(op.f('ix_salary_structures_school_id'), 'salary_structures', ['school_id'], unique=False)
    op.create_table('salary_advances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction_start_month', sa.Integer(), nullable=False),
    sa.Column('deduction_start_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_advances_school_id'), 'salary_advances', ['school_id'], unique=False)
    op.create_index(op.f('ix_salary_advances_staff_id'), 'salary_advances', ['staff_id'], unique=False)
    op.create_table('staff_salary_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('structure_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_salary_assignments_school_id'), 'staff_salary_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_salary_assignments_staff_id'), 'staff_salary_assignments', ['staff_id'], unique=False)
    op.create_table('payroll_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('da', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lop_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('esi_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_emi', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('breakdown_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disbursed_at', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['staff_salary_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'month', 'year', name='uq_payroll_staff_month')
    )
    op.create_index(op.f('ix_payroll_records_school_id'), 'payroll_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_staff_id'), 'payroll_records', ['staff_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_status'), 'payroll_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_records_status'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_staff_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_school_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index(op.f('ix_staff_salary_assignments_staff_id'), table_name='staff_salary_assignments')
    op.drop_index(op.f('ix_staff_salary_assignments_school_id'), table_name='staff_salary_assignments')
    op.drop_table('staff_salary_assignments')
    op.drop_index(op.f('ix_salary_advances_staff_id'), table_name='salary_advances')
    op.drop_index(op.f('ix_salary_advances_school_id'), table_name='salary_advances')
    op.drop_table('salary_advances')
    op.drop_index(op.f('ix_salary_structures_school_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    # ### end Alembic commands ###
