"""add_fee_management_models

Revision ID: e9b42a419f5f
Revises: e79c380aaad5
Create Date: 2026-04-21 22:30:25.495903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b42a419f5f'
down_revision: Union[str, None] = 'e79c380aaad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_discounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applicable_on', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_discounts_school_id'), 'fee_discounts', ['school_id'], unique=False)
    op.create_table('fee_structures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('late_fee_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_late_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structures_academic_year_id'), 'fee_structures', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_school_id'), 'fee_structures', ['school_id'], unique=False)
    op.create_table('fee_components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('fee_structure_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_components_fee_structure_id'), 'fee_components', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_fee_components_school_id'), 'fee_components', ['school_id'], unique=False)
    op.create_table('fee_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('fee_structure_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_structure_id', 'class_id', 'section_id', 'student_id', name='uq_fee_assignment')
    )
    op.create_index(op.f('ix_fee_assignments_class_id'), 'fee_assignments', ['class_id'], unique=False)
    op.create_index(op.f('ix_fee_assignments_fee_structure_id'), 'fee_assignments', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_fee_assignments_school_id'), 'fee_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_assignments_section_id'), 'fee_assignments', ['section_id'], unique=False)
    op.create_index(op.f('ix_fee_assignments_student_id'), 'fee_assignments', ['student_id'], unique=False)
    op.create_table('fee_dues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fee_structure_id', sa.Uuid(), nullable=False),
    sa.Column('period_label', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('late_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_structure_id', 'period_label', name='uq_fee_due_period')
    )
    op.create_index(op.f('ix_fee_dues_due_date'), 'fee_dues', ['due_date'], unique=False)
    op.create_index(op.f('ix_fee_dues_fee_structure_id'), 'fee_dues', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_fee_dues_school_id'), 'fee_dues', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_dues_status'), 'fee_dues', ['status'], unique=False)
    op.create_index(op.f('ix_fee_dues_student_id'), 'fee_dues', ['student_id'], unique=False)
    op.create_table('student_fee_discounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('discount_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discount_id'], ['fee_discounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fee_discounts_approved_by_id'), 'student_fee_discounts', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_student_fee_discounts_discount_id'), 'student_fee_discounts', ['discount_id'], unique=False)
    op.create_index(op.f('ix_student_fee_discounts_school_id'), 'student_fee_discounts', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_fee_discounts_student_id'), 'student_fee_discounts', ['student_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fee_due_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_signature', sa.String(length=500), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_due_id'], ['fee_dues.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_payment_id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_fee_payments_fee_due_id'), 'fee_payments', ['fee_due_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_recorded_by_id'), 'fee_payments', ['recorded_by_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_school_id'), 'fee_payments', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_status'), 'fee_payments', ['status'], unique=False)
    op.create_index(op.f('ix_fee_payments_student_id'), 'fee_payments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_payments_student_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_status'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_school_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_recorded_by_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_fee_due_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index(op.f('ix_student_fee_discounts_student_id'), table_name='student_fee_discounts')
    op.drop_index(op.f('ix_student_fee_discounts_school_id'), table_name='student_fee_discounts')
    op.drop_index(op.f('ix_student_fee_discounts_discount_id'), table_name='student_fee_discounts')
    op.drop_index(op.f('ix_student_fee_discounts_approved_by_id'), table_name='student_fee_discounts')
    op.drop_table('student_fee_discounts')
    op.drop_index(op.f('ix_fee_dues_student_id'), table_name='fee_dues')
    op.drop_index(op.f('ix_fee_dues_status'), table_name='fee_dues')
    op.drop_index(op.f('ix_fee_dues_school_id'), table_name='fee_dues')
    op.drop_index(op.f('ix_fee_dues_fee_structure_id'), table_name='fee_dues')
    op.drop_index(op.f('ix_fee_dues_due_date'), table_name='fee_dues')
    op.drop_table('fee_dues')
    op.drop_index(op.f('ix_fee_assignments_student_id'), table_name='fee_assignments')
    op.drop_index(op.f('ix_fee_assignments_section_id'), table_name='fee_assignments')
    op.drop_index(op.f('ix_fee_assignments_school_id'), table_name='fee_assignments')
    op.drop_index(op.f('ix_fee_assignments_fee_structure_id'), table_name='fee_assignments')
    op.drop_index(op.f('ix_fee_assignments_class_id'), table_name='fee_assignments')
    op.drop_table('fee_assignments')
    op.drop_index(op.f('ix_fee_components_school_id'), table_name='fee_components')
    op.drop_index(op.f('ix_fee_components_fee_structure_id'), table_name='fee_components')
    op.drop_table('fee_components')
    op.drop_index(op.f('ix_fee_structures_school_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_academic_year_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_fee_discounts_school_id'), table_name='fee_discounts')
    op.drop_table('fee_discounts')
    # ### end Alembic commands ###
