"""add_leave_management

Revision ID: f5c1f6572de6
Revises: 24f6cbe8b8a9
Create Date: 2026-04-21 22:54:09.179970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c1f6572de6'
down_revision: Union[str, None] = '24f6cbe8b8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'date', name='uq_school_holiday_date')
    )
    op.create_index(op.f('ix_holidays_school_id'), 'holidays', ['school_id'], unique=False)
    op.create_table('leave_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('requires_attachment', sa.Boolean(), nullable=False),
    sa.Column('default_days_per_year', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_leave_type_name')
    )
    op.create_index(op.f('ix_leave_types_school_id'), 'leave_types', ['school_id'], unique=False)
    op.create_table('leave_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type_id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('is_half_day', sa.Boolean(), nullable=False),
    sa.Column('actual_leave_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_applications_school_id'), 'leave_applications', ['school_id'], unique=False)
    op.create_index(op.f('ix_leave_applications_staff_id'), 'leave_applications', ['staff_id'], unique=False)
    op.create_index(op.f('ix_leave_applications_status'), 'leave_applications', ['status'], unique=False)
    op.create_table('staff_leave_balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'leave_type_id', 'year', name='uq_staff_leave_balance')
    )
    op.create_index(op.f('ix_staff_leave_balances_school_id'), 'staff_leave_balances', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_leave_balances_staff_id'), 'staff_leave_balances', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_leave_balances_staff_id'), table_name='staff_leave_balances')
    op.drop_index(op.f('ix_staff_leave_balances_school_id'), table_name='staff_leave_balances')
    op.drop_table('staff_leave_balances')
    op.drop_index(op.f('ix_leave_applications_status'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_staff_id'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_school_id'), table_name='leave_applications')
    op.drop_table('leave_applications')
    op.drop_index(op.f('ix_leave_types_school_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_holidays_school_id'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
